#include <stdio.h>
#include <string.h>
#include <stdlib.h>
//#include <math.h>
//#include <ctype.h>
//#include <gmp.h>
/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 * Triangle        T_(n)=n(n+1)/2      1, 3, 6, 10, 15, ...
 * Pentagonal      P_(n)=n(3n-1)/2         1, 5, 12, 22, 35, ...
 * Hexagonal       H_(n)=n(2n-1)       1, 6, 15, 28, 45, ...
 *
 * It can be verified that T_(285) = P_(165) = H_(143) = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 */

unsigned int currentValueTriangle = 1;
unsigned int currentIncrementTriangle = 2;
unsigned int currentTermTriangle = 1;
unsigned int nextTriangle()
{
    currentTermTriangle++;
    currentValueTriangle += currentIncrementTriangle++;
    return currentValueTriangle;
}
void resetTriangle()
{
    currentValueTriangle = 1;
    currentIncrementTriangle = 2;
    currentTermTriangle = 1;
}

unsigned int currentValuePent = 1;
unsigned int currentIncrementPent = 4;
unsigned int currentTermPent = 1;
unsigned int nextPent()
{
    currentTermPent++;
    currentValuePent += currentIncrementPent;
    currentIncrementPent += 3;
    return currentValuePent;
}
void resetPent()
{
    currentValuePent = 1;
    currentIncrementPent = 4;
    currentTermPent = 1;
}

unsigned int currentValueHex = 1;
unsigned int currentIncrementHex = 5;
unsigned int currentTermHex = 1;
unsigned int nextHex()
{
    currentTermHex++;
    currentValueHex += currentIncrementHex;
    currentIncrementHex += 4;
    return currentValueHex;
}
void resetHex()
{
    currentValueHex = 1;
    currentIncrementHex = 5;
    currentTermHex = 1;
}

void test()
{
    resetTriangle();
    printf("Triangle: 1 ");
    for (int i = 1; i <= 10; i++)
        printf("%d ", nextTriangle());
    printf("\n");
    resetPent();
    printf("Pentagonal: 1 ");
    for (int i = 1; i <= 10; i++)
        printf("%d ", nextPent());
    printf("\n");
    resetHex();
    printf("Hexagonal: 1 ");
    for (int i = 1; i <= 10; i++)
        printf("%d ", nextHex());
    printf("\n");
    resetTriangle();
    resetPent();
    resetHex();
}

void seekFirst() {
    while (nextTriangle() != 40755)
        ;
    printf("At triangle term %d\n", currentTermTriangle);
    while (nextPent() != 40755)
        ;
    printf("At pent term %d\n", currentTermPent);
    while (nextHex() != 40755)
        ;
    printf("At hex term %d\n", currentTermHex);
}

void findNext() {
    unsigned int t = nextTriangle(), p = nextPent(), h = nextHex();
    do {
        while (p < t)
        {
            p = nextPent();
            printf("%d %d %d\n", t, p, h);
        }
        while (h < t)
        {
            h = nextHex();
            printf("%d %d %d\n", t, p, h);
        }
        while (t < p)
        {
            t = nextTriangle();
            printf("%d %d %d\n", t, p, h);
        }
        while (p < h)
        {
            p = nextPent();
            printf("%d %d %d\n", t, p, h);
        }
    } while ((t != p) || (p != h));
    printf("%d %d %d / %d %d %d\n", t, p, h, currentTermTriangle, currentTermPent, currentTermHex);
}

int main(int argc, char **argv)
{
    test();
    seekFirst();
    findNext();
    return 0;
}
